[profile.default]
src = "contracts/evm/src"
out = "contracts/evm/out"
test = "contracts/evm/test"
script = "contracts/evm/script"
libs = ["lib"] # This tells it to look for OZ in the root's lib folder

solc = "0.8.24"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 99911155111, url = "${TENDERLY_VERIFIER_URL}" }