staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: ${TENDERLY_RPC_URL}

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com